// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTUMB9pI3Xy6KyGgYqZ6KH89gGZwc4ofw',
    appId: '1:40201082959:web:677f41b8014409b9c2b23a',
    messagingSenderId: '40201082959',
    projectId: 'yinyoga-667d9',
    authDomain: 'yinyoga-667d9.firebaseapp.com',
    storageBucket: 'yinyoga-667d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_CqBfAT3DhxP4T1NiG8ixCebM8lrDUY',
    appId: '1:40201082959:android:1e314baae24c9b58c2b23a',
    messagingSenderId: '40201082959',
    projectId: 'yinyoga-667d9',
    storageBucket: 'yinyoga-667d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZX69kn5vH7cGoSHbFR7NzUClqZy5m2E',
    appId: '1:40201082959:ios:a9f777f6ec8f6b3bc2b23a',
    messagingSenderId: '40201082959',
    projectId: 'yinyoga-667d9',
    storageBucket: 'yinyoga-667d9.firebasestorage.app',
    iosBundleId: 'com.example.yinyogaCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZX69kn5vH7cGoSHbFR7NzUClqZy5m2E',
    appId: '1:40201082959:ios:a9f777f6ec8f6b3bc2b23a',
    messagingSenderId: '40201082959',
    projectId: 'yinyoga-667d9',
    storageBucket: 'yinyoga-667d9.firebasestorage.app',
    iosBundleId: 'com.example.yinyogaCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTUMB9pI3Xy6KyGgYqZ6KH89gGZwc4ofw',
    appId: '1:40201082959:web:6f4a3ab0d6a2671cc2b23a',
    messagingSenderId: '40201082959',
    projectId: 'yinyoga-667d9',
    authDomain: 'yinyoga-667d9.firebaseapp.com',
    storageBucket: 'yinyoga-667d9.firebasestorage.app',
  );
}
